/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.test.tracker.gui;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

public class ClientForm extends javax.swing.JPanel {

    private final List<String> tripNames;

    /**
     * Creates new form ClientForm
     */
    public ClientForm(Collection<String> tripNames) {
        this.tripNames = List.copyOf(tripNames);
        initComponents();
    }
    
    public ClientFormValues getFormValues() {
        String name = clientNameTextField.getText().trim();
        String tripTitle = getComboboxValue(tripNameCombobox.getSelectedItem());
        String requirements = requirementsTextArea.getText().trim();

        List<String> options = new ArrayList<>();
        if (librariesCheckBox.isSelected()) {
            options.add(librariesCheckBox.getText());
        }
        if (nightClubsCheckBox.isSelected()) {
            options.add(nightClubsCheckBox.getText());
        }
        if (etcCheckBox.isSelected()) {
            options.add(etcCheckBox.getText());
        }

        Object selectedPrice = priceComboBox.getSelectedItem();
        String price = getComboboxValue(selectedPrice);

        return new ClientFormValues(name, tripTitle, requirements, options, price);
    }
    
    private String getComboboxValue(Object selected) {
        return selected != null ? selected.toString() : null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clientNameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tripNameCombobox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        requirementsTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        librariesCheckBox = new javax.swing.JCheckBox();
        nightClubsCheckBox = new javax.swing.JCheckBox();
        etcCheckBox = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        priceComboBox = new javax.swing.JComboBox<>();

        clientNameTextField.setToolTipText("Enter client name");
        clientNameTextField.setActionCommand("<Not Set>");
        clientNameTextField.setName("name"); // NOI18N
        clientNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientNameTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setLabelFor(clientNameTextField);
        jLabel1.setText("Enter client name");

        jLabel2.setLabelFor(tripNameCombobox);
        jLabel2.setText("Enter name of the trip");

        tripNameCombobox.setName("tripTitle"); // NOI18N
        tripNameCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(
            tripNames.toArray(String[]::new)
        ));
        tripNameCombobox.setSelectedIndex(-1);

        jLabel3.setLabelFor(requirementsTextArea);
        jLabel3.setText("Personal requirements");

        requirementsTextArea.setColumns(20);
        requirementsTextArea.setRows(5);
        requirementsTextArea.setName("requirements"); // NOI18N
        jScrollPane1.setViewportView(requirementsTextArea);

        jLabel4.setLabelFor(librariesCheckBox);
        jLabel4.setText("Click on options clinet is interesed in");

        librariesCheckBox.setText("Libraries");
        librariesCheckBox.setName("options"); // NOI18N

        nightClubsCheckBox.setText("Night clubs");
        nightClubsCheckBox.setName("options"); // NOI18N

        etcCheckBox.setText("etc");
        etcCheckBox.setName("options"); // NOI18N

        jLabel5.setLabelFor(priceComboBox);
        jLabel5.setText("Choose price from a list");

        priceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1000", "5000", "10000", "15000", "20000", "25000" }));
        priceComboBox.setSelectedIndex(-1);
        priceComboBox.setName("price"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(tripNameCombobox)
                    .addComponent(clientNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(librariesCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nightClubsCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(etcCheckBox))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(priceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(librariesCheckBox)
                    .addComponent(nightClubsCheckBox)
                    .addComponent(etcCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tripNameCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void clientNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientNameTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField clientNameTextField;
    private javax.swing.JCheckBox etcCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox librariesCheckBox;
    private javax.swing.JCheckBox nightClubsCheckBox;
    private javax.swing.JComboBox<String> priceComboBox;
    private javax.swing.JTextArea requirementsTextArea;
    private javax.swing.JComboBox<String> tripNameCombobox;
    // End of variables declaration//GEN-END:variables
}
