/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package com.mycompany.test.tracker.gui;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author yurirykov
 */
public class TripOptionsForm extends javax.swing.JPanel {
    
    private final List<ITripOptionsListener> listeners = new ArrayList<>();

    /** Creates new form TripOptionsForm */
    public TripOptionsForm() {
        initComponents();
        
        jComboBox1.addActionListener(e -> {
            handleChangeOptions();
        });
        
        jComboBox2.addActionListener(e -> {
            handleChangeOptions();
        });
        
        jComboBox3.addActionListener(e -> {
            handleChangeOptions();
        });
    }
    
    public void addTripOptionsListener(ITripOptionsListener listener) {
        listeners.add(listener);
    }
    
    public void removeTripOptionsListener(ITripOptionsListener listener) {
        listeners.remove(listener);
    }
    
    public TripOptions getFormValues() {
        Object selectedPriceRange = jComboBox1.getSelectedItem();
        Object selectedContinent = jComboBox2.getSelectedItem();
        Object selectedTemperature = jComboBox3.getSelectedItem();
        
        String priceRange = getComboboxValue(selectedPriceRange);
        String continent = getComboboxValue(selectedContinent);
        String temperature = getComboboxValue(selectedTemperature);

        return new TripOptions(priceRange, continent, temperature);
    }
    
    private void handleChangeOptions() {
        TripOptions options = getFormValues();
        fireTripOptionsSubmitted(options);
    }
    
    private String getComboboxValue(Object selected) {
        return selected != null ? selected.toString() : null;
    }
    
    private void fireTripOptionsSubmitted(TripOptions values) {
        for (ITripOptionsListener listener : listeners) {
            listener.onTripOptionsSubmitted(values);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();

        jLabel1.setLabelFor(jComboBox1);
        jLabel1.setText("Enter optimal price range");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0-10000", "10000-15000", "15000-20000", "20000-25000" }));
        jComboBox1.setSelectedIndex(-1);
        jComboBox1.setName("priceRange"); // NOI18N

        jLabel2.setText("Enter continent in wich client is interesed in");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "America", "Europe", "Asia" }));
        jComboBox2.setSelectedIndex(-1);
        jComboBox2.setToolTipText("");
        jComboBox2.setName("continent"); // NOI18N
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Choose wether country should be ");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "warm", "cold", "average" }));
        jComboBox3.setSelectedIndex(-1);
        jComboBox3.setName("temperature"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
